# Generated by Django 2.1.4 on 2019-04-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_post',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
